timestep: 0.01 ## シミュレータの時間間隔
num_beams: 1080 ## 2d Lidarのビーム数
beam_fov: 4.7 ## 2d Lidarの範囲 -270° ~ 270°
max_beam_range: 30.0 ## 2d Lidarの最大距離
num_agents: 1
steer_range: 0.4 ## ステアリングの範囲
speed_range: 10.0 ## 車両の速度範囲
render_mode: human_fast ## human or human_fast

map:
    name: IMS ## マップの名前
    ext: .png ## マップの拡張子
    line_type: center ## center race
    speed: 10.0 ## waypointの速度
    downsample: 1 ## マップのダウンサンプリング

    ## planner用の設定
    use_dynamic_speed: true ## 動的な速度を使用するかどうか
    a_lat_max: 1.0 ## 最大横加速度
    smooth_sigma: 3 ## スムージングのsigma

