name: td3
actor:
  name: 1dconv ## 1dconv mlp
  state_dim: 1080
  action_dim: 2
  hidden_dim: 256
  lr: 0.0003

critic:
  name: ${agent.actor.name}
  state_dim: ${agent.actor.state_dim}
  action_dim: ${agent.actor.action_dim}
  hidden_dim: ${agent.actor.hidden_dim}
  lr: 0.0003

gamma: 0.99
tau: 0.005
policy_noise: 0.2
noise_clip: 0.5
policy_delay: 2

